apiVersion: apps/v1
kind: Deployment
metadata:
  name: web01
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web01
        image: web01:stable
        ports:
        - containerPort: 80
